import type { AssetClass, EventSeverity, NoteStatus } from "@/lib/types";

export type AssetSeed = {
  slug: string;
  symbol: string;
  name: string;
  assetClass: AssetClass;
  subClass: string;
  exchange: string;
  sector: string;
  benchmark: string;
  description: string;
  currency: string;
  basePrice: number;
  drift: number;
  volatility: number;
  aumCr?: number | null;
  marketCapCr?: number | null;
  peRatio?: number | null;
  pbRatio?: number | null;
  roe?: number | null;
  divYield?: number | null;
  expenseRatio?: number | null;
  nav?: number | null;
  trendScore: number;
  qualityScore: number;
  valuationScore: number;
  sentimentScore: number;
  convictionScore: number;
  riskScore: number;
  tags: string[];
  classNote: string;
};

export const assetSeeds: AssetSeed[] = [
  {
    slug: "parag-parikh-flexi-cap",
    symbol: "PPFC",
    name: "Parag Parikh Flexi Cap Fund",
    assetClass: "mutual_fund",
    subClass: "Flexi Cap",
    exchange: "AMFI",
    sector: "Diversified Equity",
    benchmark: "Nifty 500 TRI",
    description:
      "A disciplined global-flexible long-duration equity fund with valuation sensitivity and quality tilt.",
    currency: "INR",
    basePrice: 118.4,
    drift: 0.0009,
    volatility: 0.010,
    aumCr: 62000,
    expenseRatio: 0.63,
    nav: 118.4,
    trendScore: 82,
    qualityScore: 91,
    valuationScore: 74,
    sentimentScore: 68,
    convictionScore: 87,
    riskScore: 34,
    tags: ["quality", "global", "long-term"],
    classNote: "Anchor research fund for quality-led allocation.",
  },
  {
    slug: "hdfc-top-100",
    symbol: "HDFC100",
    name: "HDFC Top 100 Fund",
    assetClass: "mutual_fund",
    subClass: "Large Cap",
    exchange: "AMFI",
    sector: "Large Cap Equity",
    benchmark: "Nifty 100 TRI",
    description:
      "Large-cap core fund with broad-market exposure and institutional-grade stability.",
    currency: "INR",
    basePrice: 54.9,
    drift: 0.0005,
    volatility: 0.0085,
    aumCr: 35000,
    expenseRatio: 0.72,
    nav: 54.9,
    trendScore: 74,
    qualityScore: 84,
    valuationScore: 71,
    sentimentScore: 64,
    convictionScore: 77,
    riskScore: 29,
    tags: ["core", "large-cap", "diversified"],
    classNote: "Stable large-cap exposure with measured tracking.",
  },
  {
    slug: "nippon-small-cap",
    symbol: "NIPSMALL",
    name: "Nippon India Small Cap Fund",
    assetClass: "mutual_fund",
    subClass: "Small Cap",
    exchange: "AMFI",
    sector: "Small Cap Equity",
    benchmark: "Nifty Smallcap 250 TRI",
    description:
      "High-growth small-cap allocation with higher volatility and strong alpha optionality.",
    currency: "INR",
    basePrice: 98.2,
    drift: 0.0012,
    volatility: 0.017,
    aumCr: 48000,
    expenseRatio: 0.79,
    nav: 98.2,
    trendScore: 86,
    qualityScore: 72,
    valuationScore: 61,
    sentimentScore: 73,
    convictionScore: 84,
    riskScore: 55,
    tags: ["growth", "small-cap", "alpha"],
    classNote: "High-upside sleeve requiring risk discipline.",
  },
  {
    slug: "sbi-liquid",
    symbol: "SBILIQ",
    name: "SBI Liquid Fund",
    assetClass: "mutual_fund",
    subClass: "Liquid",
    exchange: "AMFI",
    sector: "Debt",
    benchmark: "CRISIL Liquid Debt Index",
    description:
      "Low-duration cash management fund suited for parking and tactical liquidity.",
    currency: "INR",
    basePrice: 396.5,
    drift: 0.00012,
    volatility: 0.0018,
    aumCr: 42000,
    expenseRatio: 0.17,
    nav: 396.5,
    trendScore: 62,
    qualityScore: 95,
    valuationScore: 98,
    sentimentScore: 61,
    convictionScore: 78,
    riskScore: 8,
    tags: ["liquidity", "cash", "low-risk"],
    classNote: "Parking layer and short-duration cash buffer.",
  },
  {
    slug: "icici-bluechip",
    symbol: "ICICIBLUE",
    name: "ICICI Prudential Bluechip Fund",
    assetClass: "mutual_fund",
    subClass: "Large Cap",
    exchange: "AMFI",
    sector: "Large Cap Equity",
    benchmark: "Nifty 100 TRI",
    description:
      "Large-cap quality fund with emphasis on balance sheets, stability, and compounding.",
    currency: "INR",
    basePrice: 89.8,
    drift: 0.00062,
    volatility: 0.009,
    aumCr: 26000,
    expenseRatio: 0.74,
    nav: 89.8,
    trendScore: 70,
    qualityScore: 86,
    valuationScore: 68,
    sentimentScore: 66,
    convictionScore: 75,
    riskScore: 26,
    tags: ["quality", "core", "large-cap"],
    classNote: "Core large-cap building block.",
  },
  {
    slug: "quant-mid-cap",
    symbol: "QUANTMID",
    name: "Quant Mid Cap Fund",
    assetClass: "mutual_fund",
    subClass: "Mid Cap",
    exchange: "AMFI",
    sector: "Mid Cap Equity",
    benchmark: "Nifty Midcap 150 TRI",
    description:
      "Momentum-driven mid-cap strategy with tactical rebalancing and elevated turnover.",
    currency: "INR",
    basePrice: 57.3,
    drift: 0.00105,
    volatility: 0.014,
    aumCr: 31000,
    expenseRatio: 0.79,
    nav: 57.3,
    trendScore: 88,
    qualityScore: 67,
    valuationScore: 64,
    sentimentScore: 76,
    convictionScore: 85,
    riskScore: 48,
    tags: ["momentum", "mid-cap", "tactical"],
    classNote: "Aggressive mid-cap bucket with strong trend bias.",
  },
  {
    slug: "reliance-industries",
    symbol: "RELIANCE",
    name: "Reliance Industries",
    assetClass: "equity",
    subClass: "Large Cap",
    exchange: "NSE",
    sector: "Energy & Retail",
    benchmark: "Nifty 50 TRI",
    description:
      "Index heavyweight spanning energy, retail, digital, and consumer optionality.",
    currency: "INR",
    basePrice: 2989,
    drift: 0.00055,
    volatility: 0.011,
    marketCapCr: 2020000,
    peRatio: 29.4,
    pbRatio: 2.4,
    roe: 8.9,
    divYield: 0.35,
    trendScore: 75,
    qualityScore: 82,
    valuationScore: 63,
    sentimentScore: 66,
    convictionScore: 78,
    riskScore: 31,
    tags: ["blue-chip", "index-heavyweight", "energy"],
    classNote: "Core benchmark name with broad market influence.",
  },
  {
    slug: "tata-consultancy-services",
    symbol: "TCS",
    name: "Tata Consultancy Services",
    assetClass: "equity",
    subClass: "Large Cap",
    exchange: "NSE",
    sector: "IT Services",
    benchmark: "Nifty 50 TRI",
    description:
      "Cash-generative IT leader with high-quality earnings and global delivery scale.",
    currency: "INR",
    basePrice: 4012,
    drift: 0.00045,
    volatility: 0.010,
    marketCapCr: 1450000,
    peRatio: 28.2,
    pbRatio: 15.4,
    roe: 48.2,
    divYield: 1.65,
    trendScore: 68,
    qualityScore: 94,
    valuationScore: 52,
    sentimentScore: 61,
    convictionScore: 74,
    riskScore: 24,
    tags: ["it", "quality", "defensive"],
    classNote: "High-quality compounder with global revenue leverage.",
  },
  {
    slug: "hdfc-bank",
    symbol: "HDFCBANK",
    name: "HDFC Bank",
    assetClass: "equity",
    subClass: "Large Cap",
    exchange: "NSE",
    sector: "Financials",
    benchmark: "Nifty 50 TRI",
    description:
      "Private-sector banking leader with balance-sheet depth and franchise strength.",
    currency: "INR",
    basePrice: 1765,
    drift: 0.00052,
    volatility: 0.010,
    marketCapCr: 1320000,
    peRatio: 20.8,
    pbRatio: 2.8,
    roe: 15.6,
    divYield: 1.1,
    trendScore: 71,
    qualityScore: 90,
    valuationScore: 60,
    sentimentScore: 64,
    convictionScore: 77,
    riskScore: 23,
    tags: ["banking", "core", "quality"],
    classNote: "Financial core with mean-reversion and growth angle.",
  },
  {
    slug: "infosys",
    symbol: "INFY",
    name: "Infosys",
    assetClass: "equity",
    subClass: "Large Cap",
    exchange: "NSE",
    sector: "IT Services",
    benchmark: "Nifty 50 TRI",
    description:
      "Scale IT services platform with strong annuity revenue and stable margins.",
    currency: "INR",
    basePrice: 1721,
    drift: 0.00047,
    volatility: 0.0105,
    marketCapCr: 710000,
    peRatio: 27.1,
    pbRatio: 8.4,
    roe: 31.8,
    divYield: 2.0,
    trendScore: 67,
    qualityScore: 89,
    valuationScore: 56,
    sentimentScore: 63,
    convictionScore: 72,
    riskScore: 22,
    tags: ["it", "annuity", "defensive"],
    classNote: "High-quality IT benchmark with margin discipline.",
  },
  {
    slug: "itc",
    symbol: "ITC",
    name: "ITC",
    assetClass: "equity",
    subClass: "Large Cap",
    exchange: "NSE",
    sector: "Consumer Staples",
    benchmark: "Nifty 50 TRI",
    description:
      "Diversified consumer and agri business with defensive cash flows and yield support.",
    currency: "INR",
    basePrice: 442,
    drift: 0.0004,
    volatility: 0.008,
    marketCapCr: 558000,
    peRatio: 27.8,
    pbRatio: 7.4,
    roe: 28.6,
    divYield: 3.4,
    trendScore: 63,
    qualityScore: 88,
    valuationScore: 58,
    sentimentScore: 69,
    convictionScore: 73,
    riskScore: 18,
    tags: ["consumer", "dividend", "defensive"],
    classNote: "Defensive cash generator with multi-business optionality.",
  },
  {
    slug: "state-bank-of-india",
    symbol: "SBIN",
    name: "State Bank of India",
    assetClass: "equity",
    subClass: "Large Cap",
    exchange: "NSE",
    sector: "Financials",
    benchmark: "Nifty 50 TRI",
    description:
      "Public-sector banking leader with improving asset quality and high operating leverage.",
    currency: "INR",
    basePrice: 918,
    drift: 0.00058,
    volatility: 0.012,
    marketCapCr: 820000,
    peRatio: 8.5,
    pbRatio: 1.4,
    roe: 17.8,
    divYield: 1.6,
    trendScore: 74,
    qualityScore: 76,
    valuationScore: 84,
    sentimentScore: 72,
    convictionScore: 79,
    riskScore: 28,
    tags: ["banking", "value", "turnaround"],
    classNote: "Value + operating leverage bank position.",
  },
  {
    slug: "bharti-airtel",
    symbol: "BHARTIARTL",
    name: "Bharti Airtel",
    assetClass: "equity",
    subClass: "Large Cap",
    exchange: "NSE",
    sector: "Telecom",
    benchmark: "Nifty 50 TRI",
    description:
      "Telecom franchise with rising ARPU, strong spectrum positioning, and earnings normalization.",
    currency: "INR",
    basePrice: 1455,
    drift: 0.0006,
    volatility: 0.011,
    marketCapCr: 880000,
    peRatio: 32.6,
    pbRatio: 7.3,
    roe: 14.4,
    divYield: 0.3,
    trendScore: 79,
    qualityScore: 81,
    valuationScore: 59,
    sentimentScore: 74,
    convictionScore: 80,
    riskScore: 27,
    tags: ["telecom", "pricing-power", "growth"],
    classNote: "Structural telecom rerating theme.",
  },
  {
    slug: "larsen-toubro",
    symbol: "LT",
    name: "Larsen & Toubro",
    assetClass: "equity",
    subClass: "Large Cap",
    exchange: "NSE",
    sector: "Industrials",
    benchmark: "Nifty 50 TRI",
    description:
      "Engineering and capex compounder with defense, infra, and project execution exposure.",
    currency: "INR",
    basePrice: 3724,
    drift: 0.00058,
    volatility: 0.0105,
    marketCapCr: 512000,
    peRatio: 33.1,
    pbRatio: 5.7,
    roe: 17.2,
    divYield: 0.9,
    trendScore: 77,
    qualityScore: 87,
    valuationScore: 57,
    sentimentScore: 70,
    convictionScore: 82,
    riskScore: 29,
    tags: ["infra", "execution", "capex"],
    classNote: "Infrastructure and industrial cycle beneficiary.",
  },
  {
    slug: "titan-company",
    symbol: "TITAN",
    name: "Titan Company",
    assetClass: "equity",
    subClass: "Large Cap",
    exchange: "NSE",
    sector: "Consumer Discretionary",
    benchmark: "Nifty 50 TRI",
    description:
      "Lifestyle and jewelry franchise with premium consumption and brand power.",
    currency: "INR",
    basePrice: 3615,
    drift: 0.00062,
    volatility: 0.012,
    marketCapCr: 320000,
    peRatio: 81.4,
    pbRatio: 28.9,
    roe: 29.5,
    divYield: 0.4,
    trendScore: 83,
    qualityScore: 92,
    valuationScore: 42,
    sentimentScore: 77,
    convictionScore: 85,
    riskScore: 36,
    tags: ["premium", "consumer", "brand"],
    classNote: "Consumption compounder with premium positioning.",
  },
  {
    slug: "maruti-suzuki",
    symbol: "MARUTI",
    name: "Maruti Suzuki India",
    assetClass: "equity",
    subClass: "Large Cap",
    exchange: "NSE",
    sector: "Automobile",
    benchmark: "Nifty 50 TRI",
    description:
      "Market-leading passenger vehicle manufacturer with rich operating leverage.",
    currency: "INR",
    basePrice: 12244,
    drift: 0.0005,
    volatility: 0.010,
    marketCapCr: 390000,
    peRatio: 27.9,
    pbRatio: 4.1,
    roe: 14.8,
    divYield: 1.1,
    trendScore: 69,
    qualityScore: 88,
    valuationScore: 61,
    sentimentScore: 65,
    convictionScore: 74,
    riskScore: 25,
    tags: ["auto", "market-leader", "consumption"],
    classNote: "Auto cycle leader with premium market share.",
  },
  {
    slug: "sun-pharma",
    symbol: "SUNPHARMA",
    name: "Sun Pharmaceutical Industries",
    assetClass: "equity",
    subClass: "Large Cap",
    exchange: "NSE",
    sector: "Healthcare",
    benchmark: "Nifty 50 TRI",
    description:
      "Pharma major with specialty growth, domestic strength, and global optionality.",
    currency: "INR",
    basePrice: 1761,
    drift: 0.00054,
    volatility: 0.0095,
    marketCapCr: 423000,
    peRatio: 33.5,
    pbRatio: 6.9,
    roe: 18.9,
    divYield: 0.8,
    trendScore: 76,
    qualityScore: 89,
    valuationScore: 60,
    sentimentScore: 71,
    convictionScore: 79,
    riskScore: 24,
    tags: ["pharma", "specialty", "defensive-growth"],
    classNote: "Healthcare quality plus specialty upside.",
  },
  {
    slug: "gold",
    symbol: "GOLD",
    name: "Gold Futures Proxy",
    assetClass: "commodity",
    subClass: "Precious Metal",
    exchange: "MCX",
    sector: "Commodities",
    benchmark: "MCX Gold",
    description:
      "Safe-haven and macro hedge instrument for relative strength and inflation context.",
    currency: "INR",
    basePrice: 72640,
    drift: 0.00022,
    volatility: 0.009,
    trendScore: 65,
    qualityScore: 82,
    valuationScore: 88,
    sentimentScore: 62,
    convictionScore: 71,
    riskScore: 20,
    tags: ["macro-hedge", "precious-metal", "safe-haven"],
    classNote: "Core macro hedge sleeve.",
  },
  {
    slug: "silver",
    symbol: "SILVER",
    name: "Silver Futures Proxy",
    assetClass: "commodity",
    subClass: "Precious Metal",
    exchange: "MCX",
    sector: "Commodities",
    benchmark: "MCX Silver",
    description:
      "Higher beta precious metal with industrial sensitivity and volatility.",
    currency: "INR",
    basePrice: 87210,
    drift: 0.0003,
    volatility: 0.015,
    trendScore: 72,
    qualityScore: 71,
    valuationScore: 77,
    sentimentScore: 67,
    convictionScore: 73,
    riskScore: 48,
    tags: ["precious-metal", "beta", "macro"],
    classNote: "Higher-beta macro expression.",
  },
  {
    slug: "crude-oil",
    symbol: "CRUDEOIL",
    name: "Crude Oil Futures Proxy",
    assetClass: "commodity",
    subClass: "Energy",
    exchange: "MCX",
    sector: "Commodities",
    benchmark: "MCX Crude Oil",
    description:
      "Energy shock indicator used for inflation, margins, and sector sensitivity.",
    currency: "INR",
    basePrice: 6842,
    drift: 0.00015,
    volatility: 0.018,
    trendScore: 61,
    qualityScore: 63,
    valuationScore: 84,
    sentimentScore: 55,
    convictionScore: 68,
    riskScore: 62,
    tags: ["energy", "inflation", "macro"],
    classNote: "Volatile macro shock absorber and risk signal.",
  },
  {
    slug: "natural-gas",
    symbol: "NATGAS",
    name: "Natural Gas Futures Proxy",
    assetClass: "commodity",
    subClass: "Energy",
    exchange: "MCX",
    sector: "Commodities",
    benchmark: "MCX Natural Gas",
    description:
      "Supply-sensitive energy benchmark with strong seasonal and weather effects.",
    currency: "INR",
    basePrice: 264.4,
    drift: 0.00012,
    volatility: 0.021,
    trendScore: 58,
    qualityScore: 60,
    valuationScore: 85,
    sentimentScore: 53,
    convictionScore: 64,
    riskScore: 71,
    tags: ["energy", "weather", "high-volatility"],
    classNote: "Fast-moving macro input.",
  },
  {
    slug: "copper",
    symbol: "COPPER",
    name: "Copper Futures Proxy",
    assetClass: "commodity",
    subClass: "Industrial Metal",
    exchange: "MCX",
    sector: "Commodities",
    benchmark: "MCX Copper",
    description:
      "Industrial demand proxy used to assess manufacturing and global growth appetite.",
    currency: "INR",
    basePrice: 823.1,
    drift: 0.00025,
    volatility: 0.013,
    trendScore: 66,
    qualityScore: 68,
    valuationScore: 79,
    sentimentScore: 61,
    convictionScore: 69,
    riskScore: 45,
    tags: ["industrial", "growth", "cyclical"],
    classNote: "Growth-and-cycle barometer.",
  },
  {
    slug: "nifty-50",
    symbol: "NIFTY50",
    name: "Nifty 50",
    assetClass: "index",
    subClass: "Benchmark",
    exchange: "NSE",
    sector: "Indian Equities",
    benchmark: "Nifty 50 TRI",
    description:
      "India’s core benchmark used for market breadth, regime analysis, and relative strength.",
    currency: "INR",
    basePrice: 24055,
    drift: 0.00042,
    volatility: 0.009,
    trendScore: 73,
    qualityScore: 80,
    valuationScore: 70,
    sentimentScore: 67,
    convictionScore: 76,
    riskScore: 21,
    tags: ["benchmark", "market-regime"],
    classNote: "Primary benchmark and regime anchor.",
  },
  {
    slug: "india-vix",
    symbol: "INDIAVIX",
    name: "India VIX",
    assetClass: "index",
    subClass: "Volatility",
    exchange: "NSE",
    sector: "Market Risk",
    benchmark: "India VIX",
    description:
      "Market volatility gauge used to frame risk appetite and tactical positioning.",
    currency: "INR",
    basePrice: 13.8,
    drift: 0.00008,
    volatility: 0.020,
    trendScore: 47,
    qualityScore: 55,
    valuationScore: 92,
    sentimentScore: 49,
    convictionScore: 61,
    riskScore: 88,
    tags: ["volatility", "risk", "macro"],
    classNote: "Risk regime signal.",
  },
  {
    slug: "usd-inr",
    symbol: "USDINR",
    name: "USD / INR",
    assetClass: "macro",
    subClass: "FX",
    exchange: "RBI",
    sector: "Macro",
    benchmark: "RBI Reference Rate",
    description:
      "Exchange rate regime marker used to assess foreign flows, imports, and macro stability.",
    currency: "INR",
    basePrice: 83.7,
    drift: 0.00009,
    volatility: 0.0035,
    trendScore: 55,
    qualityScore: 78,
    valuationScore: 90,
    sentimentScore: 57,
    convictionScore: 63,
    riskScore: 36,
    tags: ["fx", "macro", "reference-rate"],
    classNote: "Currency regime monitor.",
  },
  {
    slug: "cpi-inflation",
    symbol: "CPI",
    name: "India CPI Inflation",
    assetClass: "macro",
    subClass: "Inflation",
    exchange: "MOSPI",
    sector: "Macro",
    benchmark: "MoSPI CPI",
    description:
      "Inflation trend driver for rates, valuations, and real-return comparisons.",
    currency: "INR",
    basePrice: 5.4,
    drift: 0.00004,
    volatility: 0.0015,
    trendScore: 53,
    qualityScore: 76,
    valuationScore: 85,
    sentimentScore: 52,
    convictionScore: 60,
    riskScore: 42,
    tags: ["inflation", "macro", "policy"],
    classNote: "Macro policy and valuation input.",
  },
  {
    slug: "10y-gsec",
    symbol: "10YGSEC",
    name: "10Y G-Sec Yield",
    assetClass: "macro",
    subClass: "Rates",
    exchange: "RBI",
    sector: "Macro",
    benchmark: "G-Sec Yield Curve",
    description:
      "The long-end rate anchor used for duration, discount-rate, and macro regime assessment.",
    currency: "INR",
    basePrice: 7.0,
    drift: -0.00002,
    volatility: 0.0012,
    trendScore: 49,
    qualityScore: 82,
    valuationScore: 89,
    sentimentScore: 50,
    convictionScore: 58,
    riskScore: 33,
    tags: ["rates", "duration", "macro"],
    classNote: "Discount rate and duration context.",
  },
];

export const watchlistSlugs = [
  "parag-parikh-flexi-cap",
  "reliance-industries",
  "hdfc-bank",
  "nifty-50",
  "gold",
  "usd-inr",
];

export const screenerPresetSeeds = [
  {
    id: "quality-core",
    name: "Quality Core",
    description: "High quality with low risk and stable trend bias.",
    filters: {
      minQualityScore: 82,
      minTrendScore: 65,
      maxRiskScore: 35,
    },
  },
  {
    id: "momentum-led",
    name: "Momentum Led",
    description: "Trend-heavy assets with strong conviction and sentiment.",
    filters: {
      minTrendScore: 78,
      minConvictionScore: 75,
      minSentimentScore: 60,
    },
  },
  {
    id: "value-opportunity",
    name: "Value Opportunity",
    description: "Higher quality assets with better valuation and tolerable risk.",
    filters: {
      minQualityScore: 70,
      minConvictionScore: 70,
      maxRiskScore: 45,
    },
  },
  {
    id: "macro-hedge",
    name: "Macro Hedge",
    description: "Inflation, volatility, and hedge assets.",
    filters: {
      assetClass: "macro",
      minTrendScore: 45,
    },
  },
];

export const settingsSeeds = [
  ["appName", "Crestfolio"],
  ["defaultPersona", "conservative_institutional"],
  ["defaultCurrency", "INR"],
  ["ollamaBaseUrl", "http://localhost:11434"],
  ["ollamaModel", "llama3.1:8b-instruct"],
  ["theme", "carbon-amber"],
  ["dataFreshness", "daily-public-plus-delayed-free"],
] as const;

export const sourceSeeds = [
  {
    key: "amfi",
    name: "AMFI NAV / scheme data",
    status: "active",
    cadence: "daily",
    freshness: "T+0 daily",
    notes: "Official mutual fund NAV backbone; free and public.",
    url: "https://www.amfiindia.com/net-asset-value/nav-download",
  },
  {
    key: "nse-reports",
    name: "NSE reports and archives",
    status: "active",
    cadence: "daily/event-driven",
    freshness: "T+0/T+1",
    notes: "Bhavcopies, corporate filings, bulk deals, index archives.",
    url: "https://www.nseindia.com/all-reports",
  },
  {
    key: "mcx-reports",
    name: "MCX public market pages",
    status: "active",
    cadence: "daily",
    freshness: "delayed/EOD",
    notes: "Historical data, spot price pages, and contract metadata.",
    url: "https://www.mcxindia.com/market-data/historical-data",
  },
  {
    key: "rbi",
    name: "RBI reference and supplement data",
    status: "active",
    cadence: "daily/weekly",
    freshness: "daily/weekly",
    notes: "Rates, reference rates, and macro indicators.",
    url: "https://www.rbi.org.in/scripts/WSSView.aspx",
  },
  {
    key: "mospi",
    name: "MoSPI CPI / GDP dashboards",
    status: "active",
    cadence: "monthly",
    freshness: "monthly",
    notes: "Inflation and macro regime context.",
    url: "https://www.mospi.gov.in/dashboard/dashboard/cpi",
  },
  {
    key: "gemini",
    name: "CrestBot (Google Gemini AI)",
    status: "active",
    cadence: "instant",
    freshness: "live",
    notes: "Google Gemini 2.5 Flash market intelligence co-pilot.",
    url: "https://ai.google.dev",
  },
];

export const baseNewsTemplates = {
  equity: [
    "Management commentary points to a steady operating backdrop and capital allocation discipline.",
    "The market is watching margin compression versus revenue resilience across the last quarter.",
    "Peer-relative momentum improved after a period of volatility in the broader sector.",
  ],
  mutual_fund: [
    "Latest NAV movement remains aligned with benchmark and category trend.",
    "Portfolio positioning suggests style consistency with controlled downside capture.",
    "Allocation and fund-flow commentary highlight a stable research profile.",
  ],
  commodity: [
    "Price action reflects macro sensitivity, global inventory cues, and currency influence.",
    "Contract activity and volatility remain important for tactical risk assessment.",
    "Commodity impulse is being driven by headline macro and supply-side considerations.",
  ],
  macro: [
    "Macro trend is affecting discount rates, risk appetite, and relative asset allocation.",
    "The latest prints are relevant for duration, valuation, and sector rotation work.",
    "A move in this indicator can alter the market regime narrative quickly.",
  ],
  etf: [
    "ETF flow and tracking behavior matter more than narrative for this sleeve.",
    "Look for spread stability, fund flows, and benchmark adherence.",
    "The wrapper is primarily useful for efficient exposure and portfolio construction.",
  ],
  index: [
    "Benchmark participation and breadth are central to the regime interpretation here.",
    "Index volatility and trend behavior are affecting stock selection across the universe.",
    "Cross-asset confirmation is useful before treating the move as durable.",
  ],
} as const;

export const eventTemplateMap: Record<
  AssetClass,
  { type: string; severity: EventSeverity; title: string }[]
> = {
  mutual_fund: [
    { type: "nav_update", severity: "low", title: "Latest NAV updated" },
    { type: "style_check", severity: "medium", title: "Style and category drift review" },
  ],
  equity: [
    { type: "results", severity: "high", title: "Quarterly results and guidance review" },
    { type: "filing", severity: "medium", title: "Corporate filing / board update" },
  ],
  commodity: [
    { type: "contract_shift", severity: "medium", title: "Contract activity / volatility shift" },
    { type: "macro_link", severity: "high", title: "Macro and inventory sensitivity update" },
  ],
  index: [
    { type: "breadth", severity: "medium", title: "Breadth and regime check" },
    { type: "volatility", severity: "high", title: "Volatility regime update" },
  ],
  macro: [
    { type: "macro_print", severity: "high", title: "Macro release and regime update" },
    { type: "rate_shift", severity: "medium", title: "Rate expectation update" },
  ],
  etf: [
    { type: "flow", severity: "medium", title: "Flow and tracking update" },
    { type: "rebalancing", severity: "low", title: "Index tracking and rebalancing note" },
  ],
};
